function get_phasor_m(matrix)
    
    disp( ...
        arrayfun( ...
            @(x) sprintf('%0.4f ∠%0.4f',abs(x),angle(x)*180/pi), ...
            matrix, ...
            'UniformOutput',false ...
        ) ...
     )
end