function carga = carga(Vn,Sn,X,fp,ef)
    %% Se não houver fp, tratar como carga resistiva.
    addpath("../utils/apoio")
    
    carga = struct( ...
        'Vn', Vn, ...
        'Sn', Sn, ...
        'fp', fp, ...
        'X', X, ...
        'I', (conj(convert_phasor(Sn,acosd(fp)))/(sqrt(3)*Vn)), ...
        'eficiencia', ef ...
    );

    disp(struct2table(carga));
end

