function trans = trans(Vp,Vs,S,X)
    Zbase_p = (Vp^2)/S;
    Zbase_s = (Vs^2)/S;
    lig_p = 'y';
    lig_s = 'y';
    trans = struct( ...
        'Vp',Vp, ...
        'Vs',Vs, ...
        'Vbp',Vp, ...
        'Vbs',Vs, ...
        'S',S, ...
        'X',X, ...
        'a',(Vp/Vs),...
        'Zbp',Zbase_p, ...
        'Zbs',Zbase_s, ...
        'lig_p',lig_p, ...
        'lig_s',lig_s ...
    );
end