function trans = trans(Vp,Vs,S,X0,X1,X2)

    Zbase_p = (Vp^2)/S;
    Zbase_s = (Vs^2)/S;
    lig_p = 'y';
    lig_s = 'y';
    trans = struct( ...
        'Vp',Vp, ...
        'Vs',Vs, ...
        'Vbp',Vp, ...
        'Vbs',Vs, ...
        'S',S, ...
        'X0',X0, ...
        'X1',X1, ...
        'X2',X2, ...
        'a',(Vp/Vs),...
        'Ibasep',(S/(sqrt(3)*Vp)),...
        'Ibases',(S/(sqrt(3)*Vs)),...
        'Zbp',Zbase_p, ...
        'Zbs',Zbase_s, ...
        'lig_p',lig_p, ...
        'lig_s',lig_s ...
    );

    disp(struct2table(trans));
end