function Z_carga = get_Zcarga_Eq(index)
    a = convert_phasor(1,120);
    dlgtitle = [index,'ª Carga Equilibrada'];
    Z_carga = inputdlg( ...
            {'Valor da Impedância de Carga:'}, ...
            dlgtitle, ...
            [1 70], ...
            {'3 + 4i'} ...
        );

    Z_carga = str2num(Z_carga);
    dlgtitle
    fprintf('\n\nImpedância de carga: %.2f j%.2f Ω\n',real(Z_carga),imag(Z_carga));
    fprintf('Fasor da Impedância de carga: %.2f/%.2f Ω\n',abs(Z_carga),angle(Z_carga)*180/pi);
end