clear;
clc;



impedancias = inputdlg( ...
    { ...
        'Digite o valor de :', ...
        'Digite o valor de :',...
        'Digite o valor de :'
    }, ...
    'Tranformação Delta <-> Y', ...
    [1 70], ...
    {'','',''} ...
);

msgbox(["Operation";"Completed"]);