function Z_carga = get_Zcarga_Eq(index)
    a = convert_phasor(1,120);
    dlgtitle = [index,'ª Carga Equilibrada'];
    Z_carga = inputdlg( ...
            {'Parte Real das Impedâncias de Carga:','Parte Imaginária das Impedâncias de Carga:'}, ...
            dlgtitle, ...
            [1 70], ...
            {'3','4'} ...
        );

    Z_carga = str2num(Z_carga{1}) + 1i*str2num(Z_carga{2});

    fprintf('\n\nImpedância de carga: %.2f j%.2f Ω\n',real(Z_carga),imag(Z_carga));
    fprintf('Fasor da Impedância de carga: %.2f/%.2f Ω\n',abs(Z_carga),angle(Z_carga)*180/pi);
end