function ligacao = get_ligacao(dlgtitle,question)

    if nargin > 1
        ligacao = questdlg( ...
            question, ...
            dlgtitle, ...
            'Y', ...
            'Δ', ...
            'Y' ...
        );
    else
        question = 'Qual é o tipo de ligação?';
        ligacao = questdlg( ...
            question, ...
            dlgtitle, ...
            'Y', ...
            'Δ', ...
            'Y' ...
        );
    end

    fprintf(['Ligacao ',ligacao]);
    
end